[target.xtensa-esp32s3-none-elf]
#runner = "probe-rs run --chip=esp32s3 --always-print-stacktrace --no-location --catch-hardfault"
runner = "espflash flash --monitor"

# [esp]
# chip = "esp32s3"
# flash_mode = "dio"       # 关键：必须是 dio
# flash_size = "16MB"      # 关键：16MB
# psram_enable = true      # 必须开启


[env]
ESP_LOG="info"


[build]
rustflags = [
  "-C", "link-arg=-nostartfiles",
  "-Z", "stack-protector=all",
]

target = "xtensa-esp32s3-none-elf"

[unstable]
build-std = ["alloc", "core"]
